/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CakeworkTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CakeworkTimeoutError.prototype);
    }
}
