/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class DrDroidTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, DrDroidTimeoutError.prototype);
    }
}
