/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as DrDroid from "../../../api";
import * as core from "../../../core";

export const SendEventsRequest: core.serialization.Schema<
    serializers.SendEventsRequest.Raw,
    DrDroid.SendEventsRequest
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("../..")).SendEventsRequestData),
});

export declare namespace SendEventsRequest {
    interface Raw {
        data: serializers.SendEventsRequestData.Raw;
    }
}
