/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DrDroid from "..";

export type Value =
    | DrDroid.StringValue
    | DrDroid.BoolValue
    | DrDroid.DoubleValue
    | DrDroid.IntValue
    | DrDroid.DatetimeValue
    | DrDroid.ArrayValue
    | DrDroid.DictValue
    | DrDroid.ObjValue;
