/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Cakework } from "@fern-api/drdroid";

export interface SendEventsRequest {
    data: Cakework.SendEventRequestData;
}
