/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { DrdroidApi } from "@fern-api/drdroid";

export interface SendEventsRequest {
    data: DrdroidApi.SendEventRequestData;
}
