/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const ArrayValues: core.serialization.ObjectSchema<serializers.ArrayValues.Raw, DrDroid.ArrayValues> =
    core.serialization.object({
        values: core.serialization.list(core.serialization.lazy(async () => (await import("..")).Value)),
    });

export declare namespace ArrayValues {
    interface Raw {
        values: serializers.Value.Raw[];
    }
}
