/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const ArrayValue: core.serialization.ObjectSchema<serializers.ArrayValue.Raw, DrDroid.ArrayValue> =
    core.serialization.object({
        arrayValue: core.serialization.property(
            "array_value",
            core.serialization.lazyObject(async () => (await import("..")).ArrayValues)
        ),
    });

export declare namespace ArrayValue {
    interface Raw {
        array_value: serializers.ArrayValues.Raw;
    }
}
