/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const BoolValue: core.serialization.ObjectSchema<serializers.BoolValue.Raw, DrDroid.BoolValue> =
    core.serialization.object({
        boolValue: core.serialization.property("bool_value", core.serialization.boolean()),
    });

export declare namespace BoolValue {
    interface Raw {
        bool_value: boolean;
    }
}
