/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const DatetimeValue: core.serialization.ObjectSchema<serializers.DatetimeValue.Raw, DrDroid.DatetimeValue> =
    core.serialization.object({
        datetimeValue: core.serialization.property("datetime_value", core.serialization.date()),
    });

export declare namespace DatetimeValue {
    interface Raw {
        datetime_value: string;
    }
}
