/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const Event: core.serialization.ObjectSchema<serializers.Event.Raw, DrDroid.Event> = core.serialization.object({
    name: core.serialization.string(),
    timestamp: core.serialization.number(),
    kvs: core.serialization.record(
        core.serialization.string(),
        core.serialization.lazy(async () => (await import("..")).Value)
    ),
});

export declare namespace Event {
    interface Raw {
        name: string;
        timestamp: number;
        kvs: Record<string, serializers.Value.Raw>;
    }
}
