/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const ObjValue: core.serialization.ObjectSchema<serializers.ObjValue.Raw, DrDroid.ObjValue> =
    core.serialization.object({
        kvlistValue: core.serialization.property(
            "kvlist_value",
            core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).KeyValue))
        ),
    });

export declare namespace ObjValue {
    interface Raw {
        kvlist_value: serializers.KeyValue.Raw[];
    }
}
