/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Cakework } from "@fern-api/drdroid";
import * as core from "../../core";

export const SendEventRequestData: core.serialization.ObjectSchema<
    serializers.SendEventRequestData.Raw,
    Cakework.SendEventRequestData
> = core.serialization.object({
    events: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Event)),
});

export declare namespace SendEventRequestData {
    interface Raw {
        events: serializers.Event.Raw[];
    }
}
