/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DrDroid from "../../api";
import * as core from "../../core";

export const StringValue: core.serialization.ObjectSchema<serializers.StringValue.Raw, DrDroid.StringValue> =
    core.serialization.object({
        stringValue: core.serialization.property("string_value", core.serialization.string()),
    });

export declare namespace StringValue {
    interface Raw {
        string_value: string;
    }
}
