/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DrdroidApiEnvironment = {
    Production: "https://ingest.drdroid.io",
} as const;

export type DrdroidApiEnvironment = typeof DrdroidApiEnvironment.Production;
