/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DrDroidEnvironment = {
    Production: "https://ingest.drdroid.io",
} as const;

export type DrDroidEnvironment = typeof DrDroidEnvironment.Production;
