/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CakeworkEnvironment = {
    Production: "https://ingest.drdroid.io",
} as const;

export type CakeworkEnvironment = typeof CakeworkEnvironment.Production;
